package com.dnpstudio.recipecorner.ui.theme

import androidx.compose.ui.graphics.Color

//Light Scheme
val primaryLight = Color(0xFF86521A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCBF)
val onPrimaryContainerLight = Color(0xFF2D1600)
val secondaryLight = Color(0xFF735943)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCBF)
val onSecondaryContainerLight = Color(0xFF291806)
val tertiaryLight = Color(0xFF596239)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDDE8B3)
val onTertiaryContainerLight = Color(0xFF171E00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF211A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF211A14)
val surfaceVariantLight = Color(0xFFF2DFD1)
val onSurfaceVariantLight = Color(0xFF51443A)
val outlineLight = Color(0xFF837469)
val outlineVariantLight = Color(0xFFD5C3B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F28)
val inverseOnSurfaceLight = Color(0xFFFDEEE3)
val inversePrimaryLight = Color(0xFFFEB876)
val surfaceDimLight = Color(0xFFE6D7CD)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E8)
val surfaceContainerLight = Color(0xFFFAEBE0)
val surfaceContainerHighLight = Color(0xFFF5E5DB)
val surfaceContainerHighestLight = Color(0xFFEFE0D5)

//Dark Scheme
val primaryDark = Color(0xFFFEB876)
val onPrimaryDark = Color(0xFF4B2800)
val primaryContainerDark = Color(0xFF6A3B02)
val onPrimaryContainerDark = Color(0xFFFFDCBF)
val secondaryDark = Color(0xFFE2C0A4)
val onSecondaryDark = Color(0xFF412C18)
val secondaryContainerDark = Color(0xFF59422D)
val onSecondaryContainerDark = Color(0xFFFFDCBF)
val tertiaryDark = Color(0xFFC1CC99)
val onTertiaryDark = Color(0xFF2C340F)
val tertiaryContainerDark = Color(0xFF424B23)
val onTertiaryContainerDark = Color(0xFFDDE8B3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEFE0D5)
val surfaceDark = Color(0xFF19120C)
val onSurfaceDark = Color(0xFFEFE0D5)
val surfaceVariantDark = Color(0xFF51443A)
val onSurfaceVariantDark = Color(0xFFD5C3B6)
val outlineDark = Color(0xFF9E8E81)
val outlineVariantDark = Color(0xFF51443A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFE0D5)
val inverseOnSurfaceDark = Color(0xFF372F28)
val inversePrimaryDark = Color(0xFF86521A)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF403830)
val surfaceContainerLowestDark = Color(0xFF130D07)
val surfaceContainerLowDark = Color(0xFF211A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)

val primaryDarkMediumContrast = Color(0xFFFFBD80)
val onPrimaryDarkMediumContrast = Color(0xFF261100)
val primaryContainerDarkMediumContrast = Color(0xFFC18347)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE6C5A8)
val onSecondaryDarkMediumContrast = Color(0xFF231203)
val secondaryContainerDarkMediumContrast = Color(0xFFA98B72)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC5D09D)
val onTertiaryDarkMediumContrast = Color(0xFF121900)
val tertiaryContainerDarkMediumContrast = Color(0xFF8B9567)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF19120C)
val onBackgroundDarkMediumContrast = Color(0xFFEFE0D5)
val surfaceDarkMediumContrast = Color(0xFF19120C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF8)
val surfaceVariantDarkMediumContrast = Color(0xFF51443A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDAC7BA)
val outlineDarkMediumContrast = Color(0xFFB0A093)
val outlineVariantDarkMediumContrast = Color(0xFF908074)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEFE0D5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF312822)
val inversePrimaryDarkMediumContrast = Color(0xFF6B3D03)
val surfaceDimDarkMediumContrast = Color(0xFF19120C)
val surfaceBrightDarkMediumContrast = Color(0xFF403830)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF130D07)
val surfaceContainerLowDarkMediumContrast = Color(0xFF211A14)
val surfaceContainerDarkMediumContrast = Color(0xFF261E18)
val surfaceContainerHighDarkMediumContrast = Color(0xFF312822)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C332C)

val primaryDarkHighContrast = Color(0xFFFFFAF8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBD80)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE6C5A8)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF7FFD4)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC5D09D)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF19120C)
val onBackgroundDarkHighContrast = Color(0xFFEFE0D5)
val surfaceDarkHighContrast = Color(0xFF19120C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF51443A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF8)
val outlineDarkHighContrast = Color(0xFFDAC7BA)
val outlineVariantDarkHighContrast = Color(0xFFDAC7BA)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEFE0D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF422200)
val surfaceDimDarkHighContrast = Color(0xFF19120C)
val surfaceBrightDarkHighContrast = Color(0xFF403830)
val surfaceContainerLowestDarkHighContrast = Color(0xFF130D07)
val surfaceContainerLowDarkHighContrast = Color(0xFF211A14)
val surfaceContainerDarkHighContrast = Color(0xFF261E18)
val surfaceContainerHighDarkHighContrast = Color(0xFF312822)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3C332C)







